version: '3.8'
services:
  db:
    image: mysql:8.0.0
    environment:
      MYSQL_ROOT_PASSWORD: ngopassword  
      MYSQL_DATABASE: ngo_portal       
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql/ngo_portal.sql:/docker-entrypoint-initdb.d/ngo_portal.sql
    networks:
      - ngo_network

  app:
    build: .
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: ngopassword  
      MYSQL_DATABASE: ngo_portal
    depends_on:
      - db
    ports:
      - "3000:3000"
    networks:
      - ngo_network

networks:
  ngo_network:
    driver: bridge

volumes:
  db_data:
